const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
let state={viewMonth:new Date(),selectedPet:"moka",selectedDate:today()};
const samplePets=[
{id:"moka",name:"モカ",type:"チンチラ",sex:"♀",icon:"🐭"},
{id:"cocoa",name:"ココア",type:"デグー",sex:"♂",icon:"🐹"},
{id:"maron",name:"まろん",type:"モルモット",sex:"♀",icon:"🐹"}
];
function makeSamples(){
 const rec={}; const weights=[552,548,551,553,549,546,548,551,550,553,538,532,540,541];
 for(let i=13;i>=0;i--){const d=new Date();d.setDate(d.getDate()-i);const ds=d.toISOString().slice(0,10);rec["moka_"+ds]={petId:"moka",date:ds,weight:weights[13-i],pellet:18,hay:"よく食べた",appetite:"◎",energy:"◎",poop:"普通",sandBath:i%2===0,sandMinutes:i%2===0?10:0,walk:i%3===0,walkMinutes:i%3===0?30:0,temp:22.5,humidity:55,memo:i===0?"砂浴びたくさんしてた😊":""};}
 rec["cocoa_"+today()]={petId:"cocoa",date:today(),weight:525,appetite:"○",energy:"◎",poop:"普通",sandBath:true,sandMinutes:8,walk:false};
 rec["maron_"+today()]={petId:"maron",date:today(),weight:820,appetite:"◎",energy:"○",poop:"普通",walk:true,walkMinutes:20};
 return rec;
}
let pets=JSON.parse(localStorage.getItem("mofu_pets")||"null")||samplePets;
let records=JSON.parse(localStorage.getItem("mofu_records")||"null")||makeSamples();
function save(){localStorage.setItem("mofu_pets",JSON.stringify(pets));localStorage.setItem("mofu_records",JSON.stringify(records));}
function key(p,d){return p+"_"+d}
function latest(petId){return Object.values(records).filter(r=>r.petId===petId&&r.weight).sort((a,b)=>a.date.localeCompare(b.date)).pop()}
function pet(id){return pets.find(p=>p.id===id)||pets[0]}
function show(view){document.querySelectorAll(".view").forEach(v=>v.classList.remove("active"));$(view).classList.add("active");document.querySelectorAll("nav button").forEach(b=>b.classList.toggle("active",b.dataset.view===view)); if(view==="calendarView")renderCalendar(); if(view==="graphView")renderGraph(); if(view==="recordView")renderRecordForm();}
document.querySelectorAll("nav button").forEach(b=>b.onclick=()=>show(b.dataset.view));
function renderHome(){const box=$("petList");box.innerHTML="";pets.forEach(p=>{const r=latest(p.id)||{};const div=document.createElement("div");div.className="petCard";div.innerHTML=`<div class="petTop"><div class="avatar">${p.icon}</div><div class="petInfo"><b>${p.name} <span style="color:var(--pink)">${p.sex}</span></b><br><small>${p.type}</small></div><div class="weightBox">${r.weight?r.weight+"g":"--"}<br><small>最新</small></div></div><div class="chips"><span class="chip">食欲 ${r.appetite||"○"}</span><span class="chip">元気 ${r.energy||"○"}</span><span class="chip">うんち ${r.poop?"○":"○"}</span>${r.sandBath?'<span class="chip">砂浴び</span>':""}${r.walk?'<span class="chip">部屋んぽ</span>':""}</div>`; div.onclick=()=>{state.selectedPet=p.id;show("recordView")}; box.appendChild(div);});}
function renderRecordForm(){const p=pet(state.selectedPet);$("recordPetMini").innerHTML=`<div class="avatar">${p.icon}</div><div><b>${p.name} ${p.sex}</b><br><small>${p.type}</small></div>`;$("date").value=state.selectedDate;loadRecord();}
function loadRecord(){const r=records[key(state.selectedPet,$("date").value)]||{};["weight","pellet","sandMinutes","walkMinutes","temp","humidity","memo"].forEach(id=>$(id).value=r[id]||"");["hay","appetite","energy","poop"].forEach(id=>{if(r[id])$(id).value=r[id]});$("sandBath").checked=!!r.sandBath;$("walk").checked=!!r.walk;}
$("date").onchange=loadRecord;
$("recordForm").onsubmit=e=>{e.preventDefault();const ds=$("date").value||today();records[key(state.selectedPet,ds)]={petId:state.selectedPet,date:ds,weight:Number($("weight").value)||0,pellet:Number($("pellet").value)||0,hay:$("hay").value,appetite:$("appetite").value,energy:$("energy").value,poop:$("poop").value,sandBath:$("sandBath").checked,sandMinutes:Number($("sandMinutes").value)||0,walk:$("walk").checked,walkMinutes:Number($("walkMinutes").value)||0,temp:Number($("temp").value)||0,humidity:Number($("humidity").value)||0,memo:$("memo").value};save();renderHome();alert("保存しました");show("homeView");}
function renderCalendar(){const y=state.viewMonth.getFullYear(),m=state.viewMonth.getMonth();$("monthTitle").textContent=`${y}年${m+1}月`;const first=new Date(y,m,1),start=new Date(y,m,1-first.getDay());$("calendar").innerHTML="";for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const ds=d.toISOString().slice(0,10);const recs=Object.values(records).filter(r=>r.date===ds);const el=document.createElement("div");el.className="day "+(d.getMonth()!==m?"other ":"")+(ds===today()?"today":"");el.innerHTML=`<div>${d.getDate()}</div><div>${recs.slice(0,3).map(()=>'<i class="dot"></i>').join("")}</div>`;el.onclick=()=>{state.selectedDate=ds;renderDay(ds)};$("calendar").appendChild(el);}renderDay(state.selectedDate);}
function renderDay(ds){$("dayTitle").textContent=ds.replaceAll("-","/")+" の記録";const rows=Object.values(records).filter(r=>r.date===ds);$("dayRecords").innerHTML=rows.length?rows.map(r=>{const p=pet(r.petId);return `<div class="dayRecord"><div class="avatar">${p.icon}</div><div><b>${p.name}</b><br><small>${r.weight||"-"}g 食欲${r.appetite||"-"} ${r.sandBath?"砂浴び"+(r.sandMinutes||"")+"分":""} ${r.walk?"部屋んぽ"+(r.walkMinutes||"")+"分":""}</small></div></div>`}).join(""):'<p class="notice">記録はまだありません。</p>';}
$("prevMonth").onclick=()=>{state.viewMonth.setMonth(state.viewMonth.getMonth()-1);renderCalendar();}
$("nextMonth").onclick=()=>{state.viewMonth.setMonth(state.viewMonth.getMonth()+1);renderCalendar();}
function renderGraph(){const tabs=$("graphPetTabs");tabs.innerHTML=pets.map(p=>`<button class="${p.id===state.selectedPet?'active':''}" data-pet="${p.id}">${p.name}</button>`).join("");tabs.querySelectorAll("button").forEach(b=>b.onclick=()=>{state.selectedPet=b.dataset.pet;renderGraph();});const rows=Object.values(records).filter(r=>r.petId===state.selectedPet&&r.weight).sort((a,b)=>a.date.localeCompare(b.date)).slice(-30);drawGraph(rows);const nums=rows.map(r=>r.weight);$("maxWeight").textContent=nums.length?Math.max(...nums)+"g":"-";$("minWeight").textContent=nums.length?Math.min(...nums)+"g":"-";$("diffWeight").textContent=nums.length>1?(nums.at(-1)-nums[0])+"g":"-";}
function drawGraph(rows){const c=$("graph"),ctx=c.getContext("2d");ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle="#f0ded9";ctx.lineWidth=1;for(let i=0;i<5;i++){let y=25+i*40;ctx.beginPath();ctx.moveTo(35,y);ctx.lineTo(330,y);ctx.stroke();}if(!rows.length)return;const vals=rows.map(r=>r.weight),min=Math.min(...vals)-5,max=Math.max(...vals)+5;ctx.strokeStyle="#f06f91";ctx.fillStyle="#f06f91";ctx.lineWidth=3;ctx.beginPath();rows.forEach((r,i)=>{const x=40+i*(285/Math.max(1,rows.length-1));const y=185-((r.weight-min)/(max-min))*150;if(i===0)ctx.moveTo(x,y);else ctx.lineTo(x,y);});ctx.stroke();rows.forEach((r,i)=>{const x=40+i*(285/Math.max(1,rows.length-1));const y=185-((r.weight-min)/(max-min))*150;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fill();});ctx.fillStyle="#7b6e6a";ctx.font="12px sans-serif";ctx.fillText(max+"g",2,28);ctx.fillText(min+"g",2,185);}
$("addPetBtn").onclick=()=>$("petDialog").showModal();$("closePet").onclick=()=>$("petDialog").close();$("savePet").onclick=()=>{const name=$("newName").value.trim();if(!name)return;const type=$("newType").value.trim()||"小動物";pets.push({id:String(Date.now()),name,type,sex:$("newSex").value,icon:type.includes("チン")?"🐭":"🐹"});save();$("petDialog").close();renderHome();}
$("exportBtn").onclick=()=>{const blob=new Blob([JSON.stringify({pets,records},null,2)],{type:"application/json"});const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="mofu_health_data.json";a.click();}
$("resetBtn").onclick=()=>{localStorage.removeItem("mofu_pets");localStorage.removeItem("mofu_records");location.reload();}
if("serviceWorker" in navigator){navigator.serviceWorker.register("service-worker.js").catch(()=>{});}
renderHome();renderCalendar();renderGraph();renderRecordForm();
